//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APIEntities : DbContext
    {
        public APIEntities()
            : base("name=APIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<SanPhamSubTheLoai> SanPhamSubTheLoais { get; set; }
        public DbSet<SanPhamTheLoai> SanPhamTheLoais { get; set; }
        public DbSet<SubTheLoai> SubTheLoais { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TheLoai> TheLoais { get; set; }
        public DbSet<CTDonHang> CTDonHangs { get; set; }
        public DbSet<DonHang> DonHangs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<SanPhamDeNghi> SanPhamDeNghis { get; set; }
        public DbSet<SanPham_Timebase> SanPham_Timebase { get; set; }
        public DbSet<TimeBase> TimeBases { get; set; }
    }
}
