//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.SanPhamSubTheLoais = new HashSet<SanPhamSubTheLoai>();
            this.SanPhamTheLoais = new HashSet<SanPhamTheLoai>();
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.SanPhamDeNghis = new HashSet<SanPhamDeNghi>();
            this.SanPhamDeNghis1 = new HashSet<SanPhamDeNghi>();
            this.SanPham_Timebase = new HashSet<SanPham_Timebase>();
        }
    
        public int Id { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotMua { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual ICollection<SanPhamSubTheLoai> SanPhamSubTheLoais { get; set; }
        public virtual ICollection<SanPhamTheLoai> SanPhamTheLoais { get; set; }
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual ICollection<SanPhamDeNghi> SanPhamDeNghis { get; set; }
        public virtual ICollection<SanPhamDeNghi> SanPhamDeNghis1 { get; set; }
        public virtual ICollection<SanPham_Timebase> SanPham_Timebase { get; set; }
    }
}
