//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoai
    {
        public TheLoai()
        {
            this.SubTheLoais = new HashSet<SubTheLoai>();
            this.SanPhamTheLoais = new HashSet<SanPhamTheLoai>();
        }
    
        public int Id { get; set; }
        public string TenTheLoai { get; set; }
    
        public virtual ICollection<SubTheLoai> SubTheLoais { get; set; }
        public virtual ICollection<SanPhamTheLoai> SanPhamTheLoais { get; set; }
    }
}
